version: '3.8'
services:

  postgresqldb:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
  
  redis:
    image: 'redis:7.4.3-alpine'
    ports:
      - '127.0.0.1:6379:6379/tcp'
    volumes:
      - 'redis_data:/data:rw'
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5

  redisinsight:
    image: 'redislabs/redisinsight:latest'
    ports:
      - '127.0.0.1:8001:8001'
    environment:
      - RITRUSTEDORIGINS=http://localhost:8001 # This is the proxy origin from browser

volumes:
  redis_data:

