apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Tempo
  - name: Loki

datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      access: proxy
      url: http://host.docker.internal:9090
      editable: true
      readOnly: false
      jsonData:
        httpMethod: POST
        exemplarTraceIdDestinations:
          - name: trace_id
            datasourceUid: tempo
    - name: Tempo
      type: tempo
      access: proxy
      orgId: 1
      url: http://tempo:3200
      basicAuth: false
      isDefault: true
      version: 1
      editable: true
      readOnly: false
      apiVersion: 1
      uid: tempo
      jsonData:
          httpMethod: GET
          tracesToLogs:
              datasourceUid: 'loki'
              filterBySpanID: false
              filterByTraceID: true
              mapTagNamesEnabled: false
              tags:
                - compose_service
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      orgId: 1
      url: http://loki:3100
      basicAuth: false
      isDefault: false
      version: 1
      readOnly: false
      editable: true
      apiVersion: 1
      jsonData:
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: '\[.+,(.+?),'
            name: TraceID
            url: $${__value.raw}