spring.data.redis.ssl.enabled=true
spring.data.redis.username=${REDIS_USERNAME:default}
spring.data.redis.password=${REDIS_PASSWORD}

spring.data.redis.lettuce.pool.max-active=32
spring.data.redis.lettuce.pool.max-idle=32
spring.data.redis.lettuce.pool.min-idle=8
spring.data.redis.lettuce.pool.max-wait=2000ms
spring.data.redis.lettuce.pool.time-between-eviction-runs=60s
