spring.data.redis.cluster.nodes=localhost:7000,localhost:7001,localhost:7002
spring.data.redis.cluster.max-redirects=2
spring.data.redis.lettuce.cluster.refresh.adaptive=true

spring.data.redis.lettuce.pool.max-active=16
spring.data.redis.lettuce.pool.max-idle=16
spring.data.redis.lettuce.pool.min-idle=4
spring.data.redis.lettuce.pool.max-wait=-1ms
spring.data.redis.lettuce.pool.time-between-eviction-runs=60s
spring.data.redis.lettuce.pool.test-on-borrow=true
