spring.data.redis.ssl.enabled=true
spring.data.redis.username=${REDIS_USERNAME:default}
spring.data.redis.password=${REDIS_PASSWORD:password}

spring.data.redis.lettuce.pool.max-active=32
spring.data.redis.lettuce.pool.max-idle=32
spring.data.redis.lettuce.pool.min-idle=8
spring.data.redis.lettuce.pool.max-wait=-1ms
spring.data.redis.lettuce.pool.time-between-eviction-runs=60s
spring.data.redis.lettuce.pool.test-on-borrow=true

ultimate.redis.security.tls-enabled=true
ultimate.redis.security.acl-username=${REDIS_USERNAME:default}
