"component: hibernate2ndlevelcache-sample":
  - spring-boot-hibernate2ndlevelcache-sample/**/*
"component: strategy-plugin":
  - spring-boot-strategy-plugin/**/*
"component: mongodb-elasticsearch":
  - spring-boot-mongodb-elasticsearch/**/*
"component: jobrunr":
  - spring-boot-jobrunr-sample/**/*
"component: dynamodb":
  - aws-dynamodb-project/**/*
"component: ses":
  - aws-ses-project/**/*
"component: sns":
  - aws-sns-project/**/*
"component: sqs":
  - aws-sqs-project/**/*
"component: kinesis":
  - aws-kinesis-project/**/*
"status: waiting-for-triage":
  - ./*
  - ./**/*
"type: documentation": docs/**/*
"type: dependency-upgrade":
  - spring-boot-hibernate2ndlevelcache-sample/pom.xml
  - spring-boot-strategy-plugin/pom.xml
  - spring-boot-mongodb-elasticsearch/pom.xml
  - spring-boot-jobrunr-sample/pom.xml
  - aws-dynamodb-project/pom.xml
  - aws-ses-project/pom.xml
  - aws-sns-project/pom.xml
  - aws-sqs-project/pom.xml
  - aws-kinesis-project/pom.xml
