image:
  file: .gitpod.Dockerfile

tasks:
  - before: sdk install mvnd
    init: mvnd verify -DskipTests=true

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - pivotal.vscode-spring-boot
    - pivotal.vscode-boot-dev-pack
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-spring-initializr
    - GabrielBB.vscode-lombok
    - redhat.java
    - ms-azuretools.vscode-docker
    - GraphQL.vscode-graphql


ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 3100
    visibility: public
  - port: 3306
    visibility: public
  - port: 4317
    visibility: public
    onOpen: ignore
  - port: 5050
    visibility: public
  - port: 5432
    visibility: public
  - port: 5601
    visibility: public
  - port: 6379
    visibility: public
  - port: 8000
    visibility: public
  - port: 8001
    visibility: public
  - port: 8080
    visibility: public
    onOpen: ignore
  - port: 8081
    visibility: public
    onOpen: open-browser
  - port: 9090
    visibility: public
    onOpen: ignore
  - port: 9200
    visibility: public
    onOpen: open-browser
  - port: 9300
    visibility: public
    onOpen: ignore
  - port: 9411
    visibility: public
