image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - pivotal.vscode-spring-boot
    - pivotal.vscode-boot-dev-pack
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-maven
    - vscjava.vscode-spring-initializr
    - GabrielBB.vscode-lombok
