image:
  file: .gitpod.Dockerfile

tasks:
  - before: sdk install mvnd
    init: mvnd verify -DskipTests

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - GabrielBB.vscode-lombok
    - richardwillis.vscode-gradle
    - GraphQL.vscode-graphql
    - GraphQL.vscode-graphql-syntax
    - redhat.java
    - VMware.vscode-boot-dev-pack
    - ms-azuretools.vscode-containers

ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 3100
    visibility: public
  - port: 3200
    visibility: public
  - port: 3306
    visibility: public
  - port: 4317
    visibility: public
    onOpen: ignore
  - port: 5050
    visibility: public
  - port: 5432
    visibility: public
  - port: 5601
    visibility: public
  - port: 6379
    visibility: public
  - port: 8000
    visibility: public
    onOpen: open-browser
  - port: 8001
    visibility: public
  - port: 8080
    visibility: public
    onOpen: open-browser
  - port: 8081
    visibility: public
    onOpen: open-browser
  - port: 9090
    visibility: public
    onOpen: open-browser
  - port: 9200
    visibility: public
    onOpen: open-browser
  - port: 9300
    visibility: public
    onOpen: ignore
  - port: 9411
    visibility: public
