version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - "1433:1433"
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password

  mysql:
    image: mysql:9.3
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=user
      - MYSQL_DATABASE=mydatabase

  postgres:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=mydatabase
  
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin

  redis:
    image: redis:8.0.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning

  redisinsight:
    image: 'redislabs/redisinsight:latest'
    ports:
      - '127.0.0.1:8001:8001'

  jenkins:
    image: jenkins/jenkins:latest
    container_name: my-jenkins
    ports:
      - "8080:8080"
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo:8.0.10
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=passcode

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=passcode
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped

volumes:
  data:
