name: boot-ultimate-redis
services:
  redis:
    image: 'redis:8.2.0-alpine'
    container_name: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5

  redisinsight:
    image: 'redislabs/redisinsight:latest'
    ports:
      - '127.0.0.1:8001:8001'

volumes:
  redis_data:
