services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - metrics-network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: postgresql://appuser:secret@host.docker.internal:5432/statsdb?sslmode=disable
    networks:
      - metrics-network

networks:
  metrics-network:
    driver: bridge
