spring:
  application.name: boot-read-replica-postgresql
  primary:
    datasource:
      password: postgres_write
      username: postgres_write
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/my_database?options=-c%20timezone=UTC 
      hikari:
        auto-commit: false
        pool-name: primaryHikariPool
        data-source-properties:
          ApplicationName: ${spring.application.name}
          serverTimezone: UTC
  replica:
    datasource:
      password: repl_password
      username: repl_user
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:15432/my_database?options=-c%20timezone=UTC 
      hikari:
        auto-commit: false
        poolName: replicaHikariPool
        data-source-properties:
          serverTimezone: UTC
################ Database #####################
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        jdbc:
          time_zone: UTC
          batch_size: 25
          lob.non_contextual_creation : true
        generate_statistics: false
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
          plan_cache_max_size: 4096
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true

# spring boot log level property
logging:
  level:
    read-replica-logger: DEBUG
jdbc:
  datasource-proxy:
    enabled: true
    multiline: false
    logging: slf4j
    query:
      logger-name: read-replica-logger
      log-level: DEBUG
      enable-logging: true
  excluded-data-source-bean-names: dataSource