services:
  postgres:
    container_name: postgres_movie_db
    image: postgres:17.6-alpine
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: moviesdb
    ports:
      - "5432:5432"
    volumes:
      - local_dev:/var/lib/postgresql/data
  redis:
    container_name: redis_movie_db
    image: redis/redis-stack:7.4.0-v6
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
   local_dev:
