services:
  mongo1:
    container_name: mongo1
    hostname: mongo1
    image: mongo:8.0.8
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "docker.for.win.host.internal:host-gateway"
    networks:
      - mongoCluster
    ports:
      - "27017:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--replSet", "myReplicaSet", "--bind_ip_all" ]

  mongo2:
    container_name: mongo2
    hostname: mongo2
    image: mongo:8.0.8
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "docker.for.win.host.internal:host-gateway"
    networks:
      - mongoCluster
    ports:
      - "27018:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--replSet", "myReplicaSet", "--bind_ip_all" ]

  mongo3:
    container_name: mongo3
    hostname: mongo3
    image: mongo:8.0.8
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "docker.for.win.host.internal:host-gateway"
    networks:
      - mongoCluster
    ports:
      - "27019:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--replSet", "myReplicaSet", "--bind_ip_all" ]

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - mongoCluster
    environment:
      #      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      #      - ME_CONFIG_MONGODB_ADMINPASSWORD=passcode
      #      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=myReplicaSet
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx2048m -Xms2048m"
    networks:
      - mongoCluster
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.0
    restart: always
    ports:
      - "5601:5601"
    networks:
      - mongoCluster
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ./elk/kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elasticsearch

networks:
  mongoCluster:
    driver: bridge

volumes:
  mongodb:
  esdata:
    driver: local
