spring.application.name=boot-spring-grpc
server.port=8080
server.shutdown=graceful
spring.main.allow-bean-definition-overriding=true
spring.jmx.enabled=false

################ Logging ####################
logging.level.com.example.grpc.spring=INFO
logging.level.org.springframework.web=INFO

################ Actuator ####################
management.endpoints.web.exposure.include=health,info,loggers,metrics
management.endpoint.health.show-details=always

################ gRPC ####################
spring.grpc.server.port=9090
spring.grpc.client.channels.local.address=localhost:9090

################ Web ####################
spring.mvc.problemdetails.enabled=true
