spring.application.name=boot-spring-grpc
server.port=8080
server.shutdown=graceful
spring.jmx.enabled=false

################ Logging ####################
logging.level.com.example.grpc.spring=INFO
logging.level.org.springframework.web=INFO

################ Actuator ####################
management.endpoints.web.exposure.include=health,info,loggers,metrics
management.endpoint.health.show-details=when_authorized

################ gRPC ####################
spring.grpc.client.channel.blog.target=localhost:9090

################ Web ####################
spring.mvc.problemdetails.enabled=true
