spring.application.name=boot-ultimate-postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/ultimate_postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Feature toggles
app.cache.cleanup-interval=60000
app.queue.worker-interval=5000
spring.mvc.problemdetails.enabled=true
