name: jpa-multitenancy-partition

on:
  push:
    paths:
      - "jpa/multitenancy/partition/**"
    branches: [main]
  pull_request:
    paths:
      - "jpa/multitenancy/partition/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "jpa/multitenancy/partition"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven"
      - name: Build with Maven
        run: ./mvnw clean verify
